# Generated by Django 2.0.1 on 2018-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=20)),
                ('lastName', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ['lastName'],
            },
        ),
    ]
