# Generated by Django 2.0.1 on 2018-01-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('body', models.TextField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='about.Member')),
            ],
        ),
    ]
